name: Update production

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  update_production:
    name: Publish production update
    type: update
    params:
      channel: production
      message: "Production update from main"
